### ISSUE TITLE
docker compose available?

### ISSUE THREAD

**Issue by PalasX** [henryford/docker-diiis#1]
I built your image, and used the docker compose for the postgres server from the diiis project, but running into errors when trying to start the diiis image. I'm assuming its because im missing volumes or open ports or other environment variables. i saw that you have an image on dockerhub as well, but also without a compose file.

can you publish the compose file you use, if any?

**Comment by henryford** [comment]
Added the docker-compose file and some comments on how to get it running :)

**Comment by PalasX** [comment]
Awesome! i eventual got the server to run by breaking out the config.ini and account/world config files so that i could edit them without a full rebuilt or by exec'ing into the container.

now to fight the good fight of getting the darn client to connect instead of giving me "cant connect to blizz" errors.

I added TTY and interactive enabled so that i could attach to the server console and create accounts, this is the YML i ended up with before you posted yours:

```
version: "3.9"
services:
  diiis:
#    image: tbueter/diiis
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 1119:1119
      - 2001:2001
      - 8081:8081
      - 9100:9109
      - 9800:9800
      - 59010:59010
    volumes:
      - ./config.ini:/diiis/config.ini
      - ./database.Worlds.config:/database.Worlds.config
      - ./database.Account.config:/database.Account.config
    networks:
      - d3postgres_postgres
networks:
  d3postgres_postgres:
    external: true

```

as you can see, i just attached to the network i was already using for the postres server that i didnt have to jump networks.
